### ISSUE TITLE
insertOrder报错

### ISSUE THREAD

**Issue by vnpy** [vnpy/vnpy_tap#20]
```
Traceback (most recent call last):
File "C:\veighna_studio\lib\threading.py", line 1016, in _bootstrap_inner
self.run()
File "C:\veighna_studio\lib\threading.py", line 953, in run
self._target(*self._args, **self._kwargs)
File "C:\veighna_studio\lib\site-packages\vnpy\event\engine.py", line 60, in _run
self._process(event)
File "C:\veighna_studio\lib\site-packages\vnpy\event\engine.py", line 73, in _process
[handler(event) for handler in self._handlers[event.type]]
File "C:\veighna_studio\lib\site-packages\vnpy\event\engine.py", line 73, in <listcomp>
[handler(event) for handler in self._handlers[event.type]]
File "C:\veighna_studio\lib\site-packages\vnpy_spreadtrading\engine.py", line 460, in process_tick_event
algo.update_tick(tick)
File "C:\veighna_studio\lib\site-packages\vnpy_spreadtrading\template.py", line 161, in update_tick
self.on_tick(tick)
File "C:\Github\work\vnpy_shiquan3\spread_trading\algo.py", line 128, in on_tick
self.quote_active_leg(new_quote_price)
File "C:\Github\work\vnpy_shiquan3\spread_trading\algo.py", line 192, in quote_active_leg
self.send_leg_order(
File "C:\Github\work\vnpy_shiquan3\spread_trading\algo.py", line 246, in send_leg_order
self.send_order(leg.vt_symbol, price, abs(leg_volume), Direction.SHORT)
File "C:\veighna_studio\lib\site-packages\vnpy_spreadtrading\template.py", line 273, in send_order
vt_orderids: list = self.algo_engine.send_order(
File "C:\veighna_studio\lib\site-packages\vnpy_spreadtrading\engine.py", line 608, in send_order
vt_orderid: str = self.main_engine.send_order(
File "C:\veighna_studio\lib\site-packages\vnpy_riskmanager\engine.py", line 61, in send_order
return self._send_order(req, gateway_name)
File "C:\veighna_studio\lib\site-packages\vnpy\trader\engine.py", line 188, in send_order
return gateway.send_order(req)
File "C:\veighna_studio\lib\site-packages\vnpy_yuanta\gateway\yuanta_gateway.py", line 127, in send_order
return self.td_api.send_order(req)
File "C:\veighna_studio\lib\site-packages\vnpy_tap\gateway\tap_gateway.

line 801, in send_order
error_id, session, order_id = self.insertOrder(order_req)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc9 in position 0: invalid continuation byte

```

**Comment by vnpy** [comment]
已经修复
